name: Build TinyStudio for Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup .NET 10.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
              
      - name: Restore dependencies
        run: dotnet restore TinyStudio/TinyStudio.csproj

      - name: Build and publish for .NET 8
        run: dotnet publish TinyStudio/TinyStudio.csproj -c Release -f net8.0 -r win-x64 -o ./publish-net8
        
      - name: Build and publish for .NET 9
        run: dotnet publish TinyStudio/TinyStudio.csproj -c Release -f net9.0 -r win-x64 -o ./publish-net9

      - name: Build and publish for .NET 10
        run: dotnet publish TinyStudio/TinyStudio.csproj -c Release -f net10.0 -r win-x64 -o ./publish-net10

      - name: Upload .NET 8 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TinyStudio-net8-windows-x64
          path: ./publish-net8

      - name: Upload .NET 9 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TinyStudio-net9-windows-x64
          path: ./publish-net9

      - name: Upload .NET 10 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TinyStudio-net10-windows-x64
          path: ./publish-net10